// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNSfTPPQT4qlNCQCKVi-ouyjf_SOsP1uc',
    appId: '1:693679137449:web:36e80b61a0ac0a70f1bfb8',
    messagingSenderId: '693679137449',
    projectId: 'fypt1-335a1',
    authDomain: 'fypt1-335a1.firebaseapp.com',
    storageBucket: 'fypt1-335a1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB27PfsRm1N9CwNBl1rUBV0Z6NZpoF_HY',
    appId: '1:693679137449:android:c46867c703f152a7f1bfb8',
    messagingSenderId: '693679137449',
    projectId: 'fypt1-335a1',
    storageBucket: 'fypt1-335a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj4OYQNDptA4TNyz9W65g6bKEPiACXjOY',
    appId: '1:693679137449:ios:a57668d315ddeb6cf1bfb8',
    messagingSenderId: '693679137449',
    projectId: 'fypt1-335a1',
    storageBucket: 'fypt1-335a1.firebasestorage.app',
    iosBundleId: 'com.example.c240faAppfinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj4OYQNDptA4TNyz9W65g6bKEPiACXjOY',
    appId: '1:693679137449:ios:a57668d315ddeb6cf1bfb8',
    messagingSenderId: '693679137449',
    projectId: 'fypt1-335a1',
    storageBucket: 'fypt1-335a1.firebasestorage.app',
    iosBundleId: 'com.example.c240faAppfinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNSfTPPQT4qlNCQCKVi-ouyjf_SOsP1uc',
    appId: '1:693679137449:web:ba5701d67c418822f1bfb8',
    messagingSenderId: '693679137449',
    projectId: 'fypt1-335a1',
    authDomain: 'fypt1-335a1.firebaseapp.com',
    storageBucket: 'fypt1-335a1.firebasestorage.app',
  );

}