// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXv5k7hEhR2l8uqaiIEn2UbjTmYnr46D4',
    appId: '1:225511218061:web:51685c569c3117bbb73bc4',
    messagingSenderId: '225511218061',
    projectId: 'c300-fyp-4e0d4',
    authDomain: 'c300-fyp-4e0d4.firebaseapp.com',
    storageBucket: 'c300-fyp-4e0d4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCojaVXwUDagP7Pk_PHSqw_ob48mIvm0EI',
    appId: '1:225511218061:android:04ae3e36d955664cb73bc4',
    messagingSenderId: '225511218061',
    projectId: 'c300-fyp-4e0d4',
    storageBucket: 'c300-fyp-4e0d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJhZ2cxIFdXTXOj3QdjtIkC62dmEtd_2Y',
    appId: '1:225511218061:ios:7392716efce4d0e5b73bc4',
    messagingSenderId: '225511218061',
    projectId: 'c300-fyp-4e0d4',
    storageBucket: 'c300-fyp-4e0d4.firebasestorage.app',
    iosBundleId: 'com.example.c240faAppfinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJhZ2cxIFdXTXOj3QdjtIkC62dmEtd_2Y',
    appId: '1:225511218061:ios:7392716efce4d0e5b73bc4',
    messagingSenderId: '225511218061',
    projectId: 'c300-fyp-4e0d4',
    storageBucket: 'c300-fyp-4e0d4.firebasestorage.app',
    iosBundleId: 'com.example.c240faAppfinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXv5k7hEhR2l8uqaiIEn2UbjTmYnr46D4',
    appId: '1:225511218061:web:a4775c580f83d703b73bc4',
    messagingSenderId: '225511218061',
    projectId: 'c300-fyp-4e0d4',
    authDomain: 'c300-fyp-4e0d4.firebaseapp.com',
    storageBucket: 'c300-fyp-4e0d4.firebasestorage.app',
  );
}
